# Generated by Django 4.0.8 on 2024-10-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stf', '0002_alter_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='flag',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
