# Generated by Django 5.1.2 on 2024-10-20 10:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stf', '0009_userwins'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserWins',
            new_name='Profile',
        ),
    ]
