# Generated by Django 5.1.2 on 2024-10-20 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stf', '0012_alter_profile_solved_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_wins',
        ),
    ]
