# Generated by Django 5.1.2 on 2024-10-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stf', '0013_remove_profile_user_wins'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_wins',
            field=models.IntegerField(default=0),
        ),
    ]
