# Generated by Django 5.1.2 on 2024-10-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stf', '0014_profile_user_wins'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
