# Generated by Django 5.1.2 on 2024-10-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stf', '0015_profile_bio_profile_birth_date_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='solved_tasks',
            field=models.CharField(default='0', max_length=10000000),
        ),
    ]
