# Generated by Django 5.1.2 on 2024-10-22 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stf', '0016_alter_profile_solved_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
