# Generated by Django 5.1.2 on 2024-11-23 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stf', '0019_task_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
    ]
