# Generated by Django 4.0.8 on 2024-10-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stf', '0003_task_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='describtion',
            field=models.CharField(default='none', max_length=1000),
            preserve_default=False,
        ),
    ]
