# Generated by Django 4.0.8 on 2024-10-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stf', '0004_task_describtion'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_wins', models.IntegerField()),
            ],
        ),
    ]
