# Generated by Django 5.1.2 on 2024-10-19 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stf', '0005_userwins'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserWins',
        ),
    ]
