# Generated by Django 5.1.2 on 2024-10-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stf', '0018_task_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='file',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
